export const CHANGE_POSTCODE_INPUT = 'CHANGE_POSTCODE_INPUT';
export const CLEAR_ALL_INPUTS = 'CLEAR_ALL_INPUTS';
export const SET_ADDRESS_OPTIONS = 'SET_ADDRESS_OPTIONS';
export const CLEAR_ADDRESS_OPTIONS = 'CLEAR_ADDRESS_OPTIONS';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
