export const CHANGE_POSTCODE_INPUT = 'CHANGE_POSTCODE_INPUT';
export const CLEAR_ALL_INPUTS = 'CLEAR_ALL_INPUTS';
export const GET_ADDRESSES_FOR_POSTCODE = 'GET_ADDRESSES_FOR_POSTCODE';
export const CLEAR_ADDRESS_OPTIONS = 'CLEAR_ADDRESS_OPTIONS';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
